version: '3.7'

services:
    mongo:
        image: mongo:3.6
        hostname: mongo
        container_name: mongo
        networks:
            - cepware
        ports:
            - "27017:27017"
        command: --bind_ip_all --smallfiles --port 27017
        volumes:
            - mongoVol:/data/configdb
            - mongoVol:/data/db
            
    orion:
       image: fiware/orion:2.0.0
       hostname: orion
       container_name: orion
       networks:
            - cepware
       links:
            - mongo
       ports:
            - "1026:1026"
       command: -dbhost mongo -logLevel INFO
            
    cygnus:
        image: fiware/cygnus-ngsi:1.9.0
        hostname: cygnus
        container_name: cygnus
        networks:
            - cepware
        links:
            - mongo
        expose:
            - "5080"
        ports:
            - "5050:5050"
            - "5080:5080"
        environment:
            - "CYGNUS_MONGO_HOSTS=mongo:27017"
            - "CYGNUS_LOG_LEVEL=DEBUG"
            - "CYGNUS_SERVICE_PORT=5050"
            - "CYGNUS_API_PORT=5080"

    idas:
       image: telefonicaiot/iotagent-ul:1.7.0
       hostname: idas
       container_name: idas
       networks:
            - cepware
       links:
         - orion
         - mongo
       expose:
         - "4041"
       ports:
         - "7896:7896"
         - "4041:4041"
       environment:
        - "IOTA_CB_HOST=orion"
        - "IOTA_CB_PORT=1026"
        - "IOTA_NORTH_PORT=4041"
        - "IOTA_REGISTRY_TYPE=mongodb"
        - "IOTA_LOG_LEVEL=DEBUG"
        - "IOTA_TIMESTAMP=true"
        - "IOTA_MONGO_HOST=mongo"
        - "IOTA_MONGO_PORT=27017"
        - "IOTA_MONGO_DB=idas"
        - "IOTA_PROVIDER_URL=http://idas:4041"
        - "CYGNUS_API_PORT=5080"
            
    jobmanager:
        image: flink:1.6.1
        hostname: jobmanager
        container_name: jobmanager
        networks:
            - cepware
        expose:
          - "6123"
        ports:
          - "8081:8081"
        command: jobmanager
        environment:
          - JOB_MANAGER_RPC_ADDRESS=jobmanager
          
    taskmanager:
        image: flink:1.6.1
        hostname: taskmanager
        container_name: taskmanager
        networks:
            - cepware
        expose:
          - "6121"
          - "6122"
        links:
          - jobmanager
        command: taskmanager
        links:
          - "jobmanager:jobmanager"
        environment:
          - JOB_MANAGER_RPC_ADDRESS=jobmanager
         
networks:
    cepware:
            
volumes:
    mongoVol: